[project]
name = 'QIGCDS'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.diplomatic-achievement-nft]
path = 'contracts/diplomatic-achievement-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.diplomatic-relations]
path = 'contracts/diplomatic-relations.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-negotiation-predictor]
path = 'contracts/quantum-negotiation-predictor.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
